[package]
name = "arceos-loader"
version = "0.1.0"
edition = "2021"
authors = ["PeizhongQiu <qiupeizhong@gmail.com>"]


[dependencies]
axstd = { path = "../../ulib/axstd", features = ["alloc"], optional = true }